[package]
name = "aura-arch"
version = "0.1.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2021"
description = "Common packaging interactions on an Arch Linux system."

[dependencies]
alpm = "2.2"
alpm-utils = "2.0"
