[workspace]
members = [
# The executable
"aura",
# Core libraries
"aura-core", "aura-arch",
# Ecosystem libraries
"r2d2-alpm",
# Documentation Generation
"doc-gen"
]

[profile.release]
lto = true
panic = "abort"
strip = true
opt-level = "z"  # Reduces final stripped size by ~20%.
codegen-units = 1
